config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  resources :questions, only: %i[index new create edit update destroy show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  def format_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    question_by_id
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      redirect_to new_question_path
    end
  end

  def edit
    question_by_id
  end

  def update
    if question_by_id.update(question_params)
      redirect_to questions_path
    else
      redirect_to edit_question_path(question_by_id)
    end
  end

  def destroy
    question_by_id.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def question_by_id
    @question = Question.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Questions', questions_path %></li>
        <li><%= link_to 'Create question', new_question_path %></li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to my world!</h1>

app/views/questions/_form.html.erb
<%= form_with model: @question do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, minlength: '2', required: true, placeholder: 'Enter title' %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body, minlength: '2', required: true, placeholder: 'Enter body' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit question</h2>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<h1>Questions:</h1>
<% @questions.each_with_index do |question, index| %>
  <h3><%= "#{index + 1}. #{question.title}" %></h3>
  <span><%= question.body %></span>
  <div>
    <span><%= question.format_created_at %></span>
  </div>
  <div>
    <%= link_to 'Show', question_path(question) %> |
    <%= link_to 'Edit', edit_question_path(question) %> |
    <%= link_to 'Delete', question_path(question), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/questions/new.html.erb
<h2>Create new question</h2>

<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<h2>Your question:</h2>

<h3><%= @question.title %></h3>
<div>
  <span><%= @question.body %></span>
</div>

<%= link_to 'Back to questions', questions_path %>